name: test
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "MESSAGE=$(git log -1 --pretty=%s)" >> $GITHUB_ENV
      - uses: hmarr/debug-action@v2