name: test
on:
  workflow_dispatch:
    inputs

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "MESSAGE_BODY=$(git log --oneline --format=%B -n 1 ${{ github.sha }} | head -n 1)" >> $GITHUB_ENV
          echo "MESSAGE='[Platform][Backend] $MESSAGE_BODY'" >> $GITHUB_ENV
      - uses: hmarr/debug-action@v2
