name: test
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hmarr/debug-action@v2
      - run: |
          git log -1 --pretty=%B